exec = gsettings set org.gnome.desktop.interface gtk-theme 'Wallbash-Gtk'
exec = gsettings set org.gnome.desktop.interface color-scheme 'prefer-dark'

general {
    col.active_border = rgba(D2D6F0ff) rgba(292E52ff) 45deg
    col.inactive_border = rgba(1B1E32ff) rgba(3C5477ff) 45deg
}

group {
    col.border_active = rgba(D2D6F0ff) rgba(292E52ff) 45deg
    col.border_inactive = rgba(1B1E32cc) rgba(3C5477cc) 45deg
    col.border_locked_active = rgba(121110ff) rgba(050505ff) 45deg
    col.border_locked_inactive = rgba(FFFFFFcc) rgba(FFFFFFcc) 45deg
}
